#!/usr/bin/env Rscript

# Copyright (c) 2017-2019 CEA
#
# This software is governed by the CeCILL license under French law and
# abiding by the rules of distribution of free software. You can use,
# modify and/ or redistribute the software under the terms of the CeCILL
# license as circulated by CEA, CNRS and INRIA at the following URL
# "http://www.cecill.info".
#
# As a counterpart to the access to the source code and rights to copy,
# modify and redistribute granted by the license, users are provided only
# with a limited warranty and the software's author, the holder of the
# economic rights, and the successive licensors have only limited
# liability.
#
# In this respect, the user's attention is drawn to the risks associated
# with loading, using, modifying and/or developing or reproducing the
# software by the user in light of its specific status of free software,
# that may mean that it is complicated to manipulate, and that also
# therefore means that it is reserved for developers and experienced
# professionals having in-depth computer knowledge. Users are therefore
# encouraged to load and test the software's suitability as regards their
# requirements in conditions enabling the security of their systems and/or
# data to be ensured and, more generally, to use and operate it in the
# same conditions as regards security.
#
# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL license and that you accept its terms.

library(tools)
library(Psytools)
library(haven)
library(dataMaid)
library(readxl)

PSYTOOLS_PSC2_DIR <- "/cveda/databank/RAW/PSC2/psytools"
PSYTOOLS_RESOURCE_FILE <- "/cveda/databank/documentation/psytools/cVEDA_resources_en.xlsx"
#PSYTOOLS_DATA_DICTIONARY_DIR <- "/cveda/databank/processed/data_dictionary"


process <- function(psc2_dir) {
    # Iterate over exported CSV Psytools files
    for (filename in list.files(psc2_dir)) {
        # The name of the questionnaire is based on the CSV file name
        name <- file_path_sans_ext(filename)

        # Read each exported CSV Psytools file into a data frame
        filepath <- file.path(psc2_dir, filename)
        COL_CLASSES = c(
            "User.code" = "character",
            "Block" = "character",
            "Trial" = "character",
            "Response.time..ms." = "numeric")
        d <- read.csv(filepath, colClasses = COL_CLASSES, stringsAsFactors = FALSE)

        # Skip files without data - they cannot be rotated!
        if (nrow(d) < 2) {
            cat(name, ": skipping file without data.", sep = "", fill = TRUE)
            next
        }
       # Extract the appropriate page from the Resources document and label
       # If no labels can be found then there will be no zsav created
        if (file.exists(PSYTOOLS_RESOURCE_FILE)) {
            require(readxl, quietly = TRUE)
            require(haven, quietly = TRUE)
            filename <- paste(unlist(strsplit(filename, "-"))[2], "EN", sep = "_")
            resources <- as.data.frame(read_xlsx(resourcesFile, sheet = filename,
                col_names = FALSE, .name_repair = make.names))
            d <- labelData(d, resources)
            write_sav(d, gsub("csv", "zsav", filepath), compress = TRUE)
            # This generates an RmdCodebook - could be set to render it to html if you prefer
            # Note the autogenerated labelling during derivations will be lost if the codebook saved at this stage
            # Commented out to avoid overwriting the codebooks generated during derivation.
            # We could modify the resources document to add the derivitive codes but it seems to be less work and more
            #   easily extendable to have the anonimisation script able to work off the labelled zsavs
#            makeCodebook(d,
#                         file = file.path(PSYTOOLS_DATA_DICTIONARY_DIR, paste0(name, '.Rmd')),
#                         render = FALSE,
#                         openResult = FALSE,
#                         codebook = TRUE,
#                         replace = TRUE)

          # # Stata requires no dots in the names and missings are represented differently
            # names(d)<-gsub('[.]', '_', names(d))
            # d[d==-666]<-tagged_na("-666")
            # d[d==-777]<-tagged_na("-777")
            # d[d==-888]<-tagged_na("-888")
            # d[d==-999]<-tagged_na("-999")
            # write_dta(d, gsub('csv', 'dta',filepath), version =14)
        }
    }
}


process(PSYTOOLS_PSC2_DIR)
